// data/categories.ts

const categories = [
	{
		title: 'Men',
		sub: [
			'T-Shirts',
			'Shirts',
			'Jeans',
			'Pants',
			'Shoes',
			'Sneakers',
			'Watches',
			'Accessories',
			'Jackets',
			'Hoodies',
			'Sweaters',
			'Underwear',
			'Socks',
			'Belts',
			'Wallets',
			'Bags',
			'Sunglasses',
			'Hats',
			'Ties',
			'Suits',
			'Formal Wear',
			'Casual Wear',
			'Sports Wear',
			'Swimwear',
			'Workout Clothes'
		]
	},
	{
		title: 'Women',
		sub: [
			'Dresses',
			'Tops',
			'Blouses',
			'T-Shirts',
			'Jeans',
			'Pants',
			'Skirts',
			'Shorts',
			'Bags',
			'Handbags',
			'Clutches',
			'Backpacks',
			'Heels',
			'Flats',
			'Sneakers',
			'Boots',
			'Sandals',
			'Jewelry',
			'Necklaces',
			'Earrings',
			'Bracelets',
			'Rings',
			'Watches',
			'Accessories',
			'Scarves',
			'Belts',
			'Sunglasses',
			'Hats',
			'Jackets',
			'Coats',
			'Sweaters',
			'Cardigans',
			'Lingerie',
			'Socks',
			'Tights',
			'Swimwear',
			'Activewear',
			'Maternity',
			'Plus Size'
		]
	},
	{
		title: 'Electronics',
		sub: [
			'Smartphones',
			'Mobile Phones',
			'Laptops',
			'Computers',
			'Desktops',
			'Tablets',
			'Headphones',
			'Earphones',
			'Speakers',
			'TVs',
			'Televisions',
			'Cameras',
			'Camcorders',
			'Gaming',
			'Consoles',
			'Controllers',
			'Accessories',
			'Chargers',
			'Cables',
			'Power Banks',
			'Smart Watches',
			'Fitness Trackers',
			'Smart Home',
			'Appliances',
			'Kitchen Electronics',
			'Audio Equipment',
			'Microphones',
			'Printers',
			'Scanners',
			'Monitors',
			'Keyboards',
			'Mice',
			'Storage Devices',
			'USB Drives',
			'External Hard Drives'
		]
	},
	{
		title: 'Home & Living',
		sub: [
			'Furniture',
			'Sofas',
			'Chairs',
			'Tables',
			'Beds',
			'Mattresses',
			'Wardrobes',
			'Dressers',
			'Decor',
			'Wall Art',
			'Paintings',
			'Mirrors',
			'Clocks',
			'Vases',
			'Candles',
			'Kitchenware',
			'Cookware',
			'Bakeware',
			'Utensils',
			'Appliances',
			'Bedding',
			'Sheets',
			'Pillows',
			'Blankets',
			'Curtains',
			'Rugs',
			'Carpets',
			'Lighting',
			'Lamps',
			'Chandeliers',
			'Bathroom',
			'Towels',
			'Shower Curtains',
			'Storage',
			'Organizers',
			'Cleaning',
			'Laundry',
			'Garden',
			'Outdoor Furniture',
			'Plants',
			'Pet Supplies'
		]
	},
	{
		title: 'Kids',
		sub: [
			'Clothing',
			'T-Shirts',
			'Dresses',
			'Pants',
			'Shorts',
			'Shoes',
			'Sneakers',
			'Sandals',
			'Toys',
			'Educational Toys',
			'Building Blocks',
			'Dolls',
			'Action Figures',
			'Board Games',
			'Puzzles',
			'Books',
			'Story Books',
			'Educational Books',
			'Coloring Books',
			'School Supplies',
			'Backpacks',
			'Lunch Boxes',
			'Stationery',
			'Baby Care',
			'Diapers',
			'Baby Food',
			'Bottles',
			'Strollers',
			'Car Seats',
			'Baby Clothes',
			'Bibs',
			'Pacifiers',
			'Bath Toys',
			'Safety Products'
		]
	},
	{
		title: 'Beauty & Personal Care',
		sub: [
			'Skincare',
			'Moisturizers',
			'Cleansers',
			'Sunscreen',
			'Face Masks',
			'Serums',
			'Makeup',
			'Foundation',
			'Lipstick',
			'Eyeshadow',
			'Mascara',
			'Blush',
			'Hair Care',
			'Shampoo',
			'Conditioner',
			'Hair Styling',
			'Hair Tools',
			'Fragrances',
			'Perfumes',
			'Colognes',
			'Body Care',
			'Soaps',
			'Body Wash',
			'Lotions',
			'Deodorants',
			'Oral Care',
			'Toothbrushes',
			'Toothpaste',
			'Mouthwash',
			"Men's Grooming",
			'Shaving',
			'Beard Care',
			'Nail Care',
			'Tools',
			'Brushes',
			'Mirrors'
		]
	},
	{
		title: 'Sports & Outdoors',
		sub: [
			'Fitness',
			'Gym Equipment',
			'Weights',
			'Yoga Mats',
			'Resistance Bands',
			'Sports Clothing',
			'Athletic Shoes',
			'Running Shoes',
			'Team Sports',
			'Football',
			'Basketball',
			'Soccer',
			'Tennis',
			'Golf',
			'Swimming',
			'Cycling',
			'Bikes',
			'Helmets',
			'Outdoor Gear',
			'Camping',
			'Tents',
			'Sleeping Bags',
			'Hiking',
			'Backpacks',
			'Water Bottles',
			'Fishing',
			'Hunting',
			'Water Sports',
			'Surfing',
			'Kayaking',
			'Skiing',
			'Snowboarding',
			'Exercise Machines',
			'Treadmills',
			'Ellipticals'
		]
	},
	{
		title: 'Automotive',
		sub: [
			'Car Parts',
			'Engine Parts',
			'Brakes',
			'Tires',
			'Wheels',
			'Batteries',
			'Oils',
			'Fluids',
			'Car Care',
			'Washing',
			'Waxing',
			'Interior Care',
			'Accessories',
			'Seat Covers',
			'Floor Mats',
			'Phone Mounts',
			'Dash Cams',
			'GPS',
			'Navigation',
			'Audio',
			'Speakers',
			'Subwoofers',
			'Tools',
			'Wrenches',
			'Screwdrivers',
			'Jacks',
			'Motorcycle',
			'Helmets',
			'Jackets',
			'Gloves',
			'Truck Parts',
			'RV Parts',
			'Boat Parts'
		]
	},
	{
		title: 'Books & Media',
		sub: [
			'Books',
			'Fiction',
			'Non-Fiction',
			'Biography',
			'Self-Help',
			'Business',
			'Cooking',
			'Travel',
			'Science',
			'History',
			"Children's Books",
			'Textbooks',
			'Magazines',
			'Newspapers',
			'E-Books',
			'Audiobooks',
			'Music',
			'CDs',
			'Vinyl Records',
			'Digital Downloads',
			'Movies',
			'DVDs',
			'Blu-rays',
			'Digital Movies',
			'TV Shows',
			'Documentaries',
			'Educational',
			'Language Learning',
			'Reference',
			'Dictionaries',
			'Encyclopedias'
		]
	},
	{
		title: 'Health & Wellness',
		sub: [
			'Vitamins',
			'Supplements',
			'Protein',
			'Weight Loss',
			'Fitness Supplements',
			'Herbs',
			'Natural Remedies',
			'Medical Devices',
			'Blood Pressure Monitors',
			'Thermometers',
			'First Aid',
			'Bandages',
			'Antiseptics',
			'Pain Relief',
			'Medications',
			'Prescription',
			'Over-the-Counter',
			'Mobility Aids',
			'Wheelchairs',
			'Walkers',
			'Canes',
			'Orthopedic',
			'Braces',
			'Supports',
			'Massage',
			'Therapy',
			'Wellness',
			'Meditation',
			'Aromatherapy',
			'Essential Oils'
		]
	},
	{
		title: 'Fashion Accessories',
		sub: [
			'Jewelry',
			'Necklaces',
			'Earrings',
			'Bracelets',
			'Rings',
			'Watches',
			'Sunglasses',
			'Eyeglasses',
			'Belts',
			'Wallets',
			'Purses',
			'Handbags',
			'Backpacks',
			'Scarves',
			'Hats',
			'Caps',
			'Gloves',
			'Socks',
			'Tights',
			'Hair Accessories',
			'Clips',
			'Bands',
			'Wigs',
			'Extensions',
			'Ties',
			'Bow Ties',
			'Cufflinks',
			'Pocket Squares',
			'Umbrellas',
			'Rain Gear',
			'Travel Accessories',
			'Luggage',
			'Suitcases',
			'Travel Bags'
		]
	},
	{
		title: 'Food & Beverages',
		sub: [
			'Groceries',
			'Fresh Produce',
			'Vegetables',
			'Fruits',
			'Meat',
			'Poultry',
			'Seafood',
			'Dairy',
			'Milk',
			'Cheese',
			'Yogurt',
			'Beverages',
			'Coffee',
			'Tea',
			'Juices',
			'Sodas',
			'Water',
			'Snacks',
			'Chips',
			'Nuts',
			'Crackers',
			'Candy',
			'Chocolate',
			'Baking',
			'Flour',
			'Sugar',
			'Spices',
			'Oils',
			'Condiments',
			'Sauces',
			'Organic',
			'Gluten-Free',
			'Vegan',
			'Keto',
			'Paleo',
			'Supplements',
			'Protein Bars',
			'Energy Drinks'
		]
	},
	{
		title: 'Office & Business',
		sub: [
			'Office Supplies',
			'Paper',
			'Pens',
			'Pencils',
			'Markers',
			'Notebooks',
			'Folders',
			'Binders',
			'Desk Organizers',
			'Furniture',
			'Desks',
			'Chairs',
			'Filing Cabinets',
			'Technology',
			'Computers',
			'Printers',
			'Scanners',
			'Projectors',
			'Software',
			'Business Software',
			'Accounting',
			'CRM',
			'Marketing',
			'Business Cards',
			'Signage',
			'Presentations',
			'Whiteboards',
			'Bulletin Boards',
			'Conference Equipment',
			'Audio Visual',
			'Security',
			'Safes',
			'Locks'
		]
	}
];

export default categories;
