version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: webone_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: webone_db
      POSTGRES_USER: webone_user
      POSTGRES_PASSWORD: webone_password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - webone_network

volumes:
  postgres_data:

networks:
  webone_network:
    driver: bridge
